import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';
import { Icon } from '@iconify/react';

/**
 *
 * @returns {JSX.Element}
 */
const Home: NextPage = (): JSX.Element => {
	return (
		<>
			<Head>
				<title>José Thomaz</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to <span style={{ color: '#5271ff' }}>my blog</span>
				</h1>

				<p className={styles.description}>
					My name is <code className={styles.code}>José Thomaz</code> and I'm a{' '}
					<br />
					Software Engineer based in São Paulo, Brazil 🇧🇷.
				</p>

				<div className={styles.grid}>
					<Link href="/blog">
						<div className={styles.card}>
							<>
								<h2>Blog &rarr;</h2>
								<p>Articles that I write to exercise and share my knowledge.</p>
							</>
						</div>
					</Link>

					<Link href="/about">
						<div className={styles.card}>
							<>
								<h2>About me &rarr;</h2>
								<p>Learn more about me, what I study and stuff that I do!</p>
							</>
						</div>
					</Link>

					<Link href="/social-media">
						<div className={styles.card}>
							<>
								<h2>Social media &rarr;</h2>
								<p>My social media.</p>
							</>
						</div>
					</Link>

					<Link href="/reading-list">
						<div className={styles.card}>
							<>
								<h2>Reading list &rarr;</h2>
								<p>
									List of books related to technology that I've read or want to
									read.
								</p>
							</>
						</div>
					</Link>
				</div>
			</main>

			<footer className={styles.footer}>
				<p>
					{new Date().getFullYear()} - {''}
				</p>
				<div className={styles.footerIcons}>
					<Icon icon="academicons:stackoverflow" fontSize={25} />
					<Icon icon="ant-design:github-filled" fontSize={25} />
					<Icon icon="ant-design:twitter-outlined" fontSize={25} />
					<Icon icon="ant-design:linkedin-filled" fontSize={25} />
				</div>
			</footer>
		</>
	);
};

export default Home;
